import Head from "next/head";
import Hero from "../components/Hero";
import About from "../components/About";
import { AboutData } from "../components/AboutData";
import Instagram from "../components/Instagram";

export default function Home() {
  return (
    <div>
      <Head>
        <title>
          Web App
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Oji's Website" message="I created this simple website using Next.js" />
      <About slides={AboutData} />
      <Instagram />
    </div>
  )
}
